CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','INACTIVE');
CREATE TYPE "RoleName" AS ENUM ('ADMINISTRATEUR','RESPONSABLE_QHSE','ASSISTANT_QHSE','CONTROLEUR_QUALITE','CHEF_PRODUCTION','OPERATEUR','AUDITEUR','CONSULTATION');
CREATE TYPE "DocumentStatus" AS ENUM ('DRAFT','REVIEW','APPROVED','ACTIVE','SUPERSEDED','ARCHIVED');
CREATE TYPE "EpiFrequency" AS ENUM ('DAILY','ANNUAL');
CREATE TYPE "EpiMovementType" AS ENUM ('RECEIPT','DAILY_DISTRIBUTION','ANNUAL_DISTRIBUTION','REPLACEMENT','LOSS','DAMAGE','ADJUSTMENT');
CREATE TYPE "SyncStatus" AS ENUM ('PENDING','SYNCED','CONFLICT','FAILED');
CREATE TYPE "SafetyTalkStatus" AS ENUM ('DRAFT','APPROVED','DELIVERED');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"firstName" TEXT NOT NULL,"lastName" TEXT NOT NULL,"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"employeeId" TEXT UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Role" ("id" TEXT PRIMARY KEY,"name" "RoleName" NOT NULL UNIQUE);
CREATE TABLE "Permission" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE);
CREATE TABLE "UserRole" ("userId" TEXT NOT NULL,"roleId" TEXT NOT NULL,PRIMARY KEY("userId","roleId"));
CREATE TABLE "RolePermission" ("roleId" TEXT NOT NULL,"permissionId" TEXT NOT NULL,PRIMARY KEY("roleId","permissionId"));
CREATE TABLE "RefreshToken" ("id" TEXT PRIMARY KEY,"tokenHash" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"userId" TEXT,"action" TEXT NOT NULL,"module" TEXT NOT NULL,"entityId" TEXT,"oldValue" JSONB,"newValue" JSONB,"ipAddress" TEXT,"userAgent" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Document" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"category" TEXT NOT NULL,"status" "DocumentStatus" NOT NULL DEFAULT 'DRAFT',"currentVersion" INTEGER NOT NULL DEFAULT 1,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DocumentVersion" ("id" TEXT PRIMARY KEY,"documentId" TEXT NOT NULL,"version" INTEGER NOT NULL,"fileName" TEXT NOT NULL,"storagePath" TEXT NOT NULL,"checksum" TEXT,"status" "DocumentStatus" NOT NULL DEFAULT 'DRAFT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("documentId","version"));
CREATE TABLE "Attachment" ("id" TEXT PRIMARY KEY,"originalName" TEXT NOT NULL,"storagePath" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"size" INTEGER NOT NULL,"sha256" TEXT,"uploadedById" TEXT,"documentId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Epi" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"frequency" "EpiFrequency" NOT NULL,"unit" TEXT NOT NULL DEFAULT 'piece',"annualValidityDays" INTEGER,"minStock" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE "Employee" ("id" TEXT PRIMARY KEY,"matricule" TEXT NOT NULL UNIQUE,"firstName" TEXT NOT NULL,"lastName" TEXT NOT NULL,"department" TEXT,"position" TEXT,"active" BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE "EpiAssignment" ("id" TEXT PRIMARY KEY,"employeeId" TEXT NOT NULL,"epiId" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"distributedAt" TIMESTAMP(3) NOT NULL,"renewalAt" TIMESTAMP(3),"condition" TEXT,"reason" TEXT);
CREATE TABLE "EpiMovement" ("id" TEXT PRIMARY KEY,"epiId" TEXT NOT NULL,"type" "EpiMovementType" NOT NULL,"quantity" INTEGER NOT NULL,"employeeId" TEXT,"distributionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"userId" TEXT,"note" TEXT);
CREATE TABLE "DailyHeadcount" ("id" TEXT PRIMARY KEY,"date" TIMESTAMP(3) NOT NULL UNIQUE,"headcount" INTEGER NOT NULL,"source" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "SyncItem" ("id" TEXT PRIMARY KEY,"clientLocalId" TEXT NOT NULL UNIQUE,"entity" TEXT NOT NULL,"entityId" TEXT,"operation" TEXT NOT NULL,"payload" JSONB NOT NULL,"status" "SyncStatus" NOT NULL DEFAULT 'PENDING',"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"syncedAt" TIMESTAMP(3));
CREATE TABLE "SafetyEvent" ("id" TEXT PRIMARY KEY,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"occurredAt" TIMESTAMP(3) NOT NULL,"severity" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ControlTemplate" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "QualityControl" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"line" TEXT,"product" TEXT,"format" TEXT,"lotNumber" TEXT,"shift" TEXT,"controlDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"status" TEXT NOT NULL DEFAULT 'DRAFT',"result" TEXT,"notes" TEXT,"createdById" TEXT,"templateId" TEXT);
CREATE TABLE "ControlPoint" ("id" TEXT PRIMARY KEY,"templateId" TEXT NOT NULL,"code" TEXT NOT NULL,"label" TEXT NOT NULL,"type" TEXT NOT NULL,"required" BOOLEAN NOT NULL DEFAULT FALSE,"critical" BOOLEAN NOT NULL DEFAULT FALSE,"minValue" DOUBLE PRECISION,"maxValue" DOUBLE PRECISION,"choices" JSONB,"order" INTEGER NOT NULL DEFAULT 0,UNIQUE("templateId","code"));
CREATE TABLE "ControlResult" ("id" TEXT PRIMARY KEY,"controlId" TEXT NOT NULL,"pointId" TEXT NOT NULL,"value" JSONB,"compliant" BOOLEAN,"comment" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("controlId","pointId"));
CREATE TABLE "NonConformity" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"description" TEXT,"severity" INTEGER NOT NULL DEFAULT 1,"status" TEXT NOT NULL DEFAULT 'OPEN',"source" TEXT,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"qualityControlId" TEXT);
CREATE TABLE "Action" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"description" TEXT,"status" TEXT NOT NULL DEFAULT 'OPEN',"priority" INTEGER NOT NULL DEFAULT 2,"dueDate" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"responsibleId" TEXT,"nonConformityId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Risk" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"hazard" TEXT NOT NULL,"activity" TEXT,"severity" INTEGER NOT NULL,"probability" INTEGER NOT NULL,"control" INTEGER NOT NULL DEFAULT 1,"score" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"measures" TEXT,"reviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "HaccpRecord" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"process" TEXT NOT NULL,"step" TEXT NOT NULL,"hazard" TEXT NOT NULL,"ccp" BOOLEAN NOT NULL DEFAULT FALSE,"criticalLimit" TEXT,"monitoring" TEXT,"result" TEXT,"correctiveAction" TEXT,"recordDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "QhseAudit" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"reference" TEXT,"auditDate" TIMESTAMP(3) NOT NULL,"auditorId" TEXT,"status" TEXT NOT NULL DEFAULT 'PLANNED',"score" DOUBLE PRECISION,"findings" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "EnvironmentRecord" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"type" TEXT NOT NULL,"value" DOUBLE PRECISION,"unit" TEXT,"site" TEXT,"recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"notes" TEXT);
CREATE TABLE "Training" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"trainer" TEXT,"scheduledAt" TIMESTAMP(3) NOT NULL,"durationHours" DOUBLE PRECISION,"status" TEXT NOT NULL DEFAULT 'PLANNED',"participants" JSONB,"expiryAt" TIMESTAMP(3));
CREATE TABLE "Equipment" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"category" TEXT,"location" TEXT,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"lastInspectionAt" TIMESTAMP(3),"nextInspectionAt" TIMESTAMP(3),"notes" TEXT);
CREATE TABLE "SafetyTalk" ("id" TEXT PRIMARY KEY,"weekStart" TIMESTAMP(3) NOT NULL UNIQUE,"weekEnd" TIMESTAMP(3) NOT NULL,"title" TEXT NOT NULL,"summary" TEXT NOT NULL,"status" "SafetyTalkStatus" NOT NULL DEFAULT 'DRAFT',"generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"approvedAt" TIMESTAMP(3),"createdById" TEXT);

ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_roleId_fkey" FOREIGN KEY("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_createdById_fkey" FOREIGN KEY("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DocumentVersion" ADD CONSTRAINT "DocumentVersion_documentId_fkey" FOREIGN KEY("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_uploadedById_fkey" FOREIGN KEY("uploadedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_documentId_fkey" FOREIGN KEY("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EpiAssignment" ADD CONSTRAINT "EpiAssignment_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EpiAssignment" ADD CONSTRAINT "EpiAssignment_epiId_fkey" FOREIGN KEY("epiId") REFERENCES "Epi"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EpiMovement" ADD CONSTRAINT "EpiMovement_epiId_fkey" FOREIGN KEY("epiId") REFERENCES "Epi"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EpiMovement" ADD CONSTRAINT "EpiMovement_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EpiMovement" ADD CONSTRAINT "EpiMovement_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "QualityControl" ADD CONSTRAINT "QualityControl_createdById_fkey" FOREIGN KEY("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "QualityControl" ADD CONSTRAINT "QualityControl_templateId_fkey" FOREIGN KEY("templateId") REFERENCES "ControlTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ControlPoint" ADD CONSTRAINT "ControlPoint_templateId_fkey" FOREIGN KEY("templateId") REFERENCES "ControlTemplate"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ControlResult" ADD CONSTRAINT "ControlResult_controlId_fkey" FOREIGN KEY("controlId") REFERENCES "QualityControl"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ControlResult" ADD CONSTRAINT "ControlResult_pointId_fkey" FOREIGN KEY("pointId") REFERENCES "ControlPoint"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ControlResult" ADD CONSTRAINT "ControlResult_createdById_fkey" FOREIGN KEY("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NonConformity" ADD CONSTRAINT "NonConformity_qualityControlId_fkey" FOREIGN KEY("qualityControlId") REFERENCES "QualityControl"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Action" ADD CONSTRAINT "Action_responsibleId_fkey" FOREIGN KEY("responsibleId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Action" ADD CONSTRAINT "Action_nonConformityId_fkey" FOREIGN KEY("nonConformityId") REFERENCES "NonConformity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "QhseAudit" ADD CONSTRAINT "QhseAudit_auditorId_fkey" FOREIGN KEY("auditorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SafetyTalk" ADD CONSTRAINT "SafetyTalk_createdById_fkey" FOREIGN KEY("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "AuditLog_module_entityId_idx" ON "AuditLog"("module","entityId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "Attachment_documentId_idx" ON "Attachment"("documentId");
CREATE INDEX "EpiAssignment_employeeId_epiId_idx" ON "EpiAssignment"("employeeId","epiId");
CREATE INDEX "EpiMovement_epiId_distributionDate_idx" ON "EpiMovement"("epiId","distributionDate");
CREATE INDEX "NonConformity_status_occurredAt_idx" ON "NonConformity"("status","occurredAt");
CREATE INDEX "Action_status_dueDate_idx" ON "Action"("status","dueDate");
CREATE INDEX "QualityControl_controlDate_idx" ON "QualityControl"("controlDate");
CREATE INDEX "QualityControl_status_idx" ON "QualityControl"("status");
CREATE INDEX "ControlPoint_templateId_order_idx" ON "ControlPoint"("templateId","order");
CREATE INDEX "Risk_score_idx" ON "Risk"("score");
