import { Roles } from '../common/roles.decorator';
import { RoleName } from '@prisma/client';
import { CreateNcDto,UpdateNcDto,CreateNcContainmentActionDto,UpdateNcContainmentActionDto,CreateNcCauseDto,UpdateNcCauseDto,CreateNcCostDto,UpdateNcCostDto } from './dto/nc.dto';
import { CreateActionDto,UpdateActionDto,CreateActionCauseDto,UpdateActionCauseDto,CreateActionExtensionDto } from './dto/action.dto';
import { CreateRiskDto,UpdateRiskDto,CreateRiskMeasureDto,UpdateRiskMeasureDto } from './dto/risk.dto';
import { CreateAuditDto,UpdateAuditDto,CreateAuditFindingDto,UpdateAuditFindingDto } from './dto/audit.dto';
import {Body,Controller,Delete,Get,Param,Patch,Post,Query} from '@nestjs/common'; import {BusinessService} from './business.service';
@Controller('business') export class BusinessController {constructor(private s:BusinessService){}
@Get('dashboard') dashboard(){return this.s.dashboard()}
@Get('quality-controls') qualityList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.qualityList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('quality-controls') qualityCreate(@Body() b:any){return this.s.qualityCreate(b)} @Patch('quality-controls/:id') qualityUpdate(@Param('id')id:string,@Body()b:any){return this.s.qualityUpdate(id,b)} @Delete('quality-controls/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) qualityDelete(@Param('id')id:string){return this.s.qualityDelete(id)}
@Get('non-conformities') ncList(@Query('status')status?:string,@Query('take')take?:string,@Query('skip')skip?:string){return this.s.ncList(status,take?Number(take):undefined,skip?Number(skip):undefined)} @Get('non-conformities/:id') ncGet(@Param('id')id:string){return this.s.ncGet(id)} @Post('non-conformities') ncCreate(@Body()b:CreateNcDto){return this.s.ncCreate(b)} @Patch('non-conformities/:id') ncUpdate(@Param('id')id:string,@Body()b:UpdateNcDto){return this.s.ncUpdate(id,b)} @Delete('non-conformities/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) ncDelete(@Param('id')id:string){return this.s.ncDelete(id)}
@Get('nc-dashboard') ncDashboard(){return this.s.ncDashboard()} @Get('nc-settings') ncSettingsGet(){return this.s.ncSettingsGet()} @Patch('nc-settings') ncSettingsUpdate(@Body()b:any){return this.s.ncSettingsUpdate(b)}
@Post('non-conformities/:id/close') ncClose(@Param('id')id:string,@Body()b:any){return this.s.ncClose(id,b)} @Post('non-conformities/:id/reopen') ncReopen(@Param('id')id:string){return this.s.ncReopen(id)} @Post('non-conformities/:id/effectiveness') ncEffectivenessCheck(@Param('id')id:string,@Body()b:any){return this.s.ncEffectivenessCheck(id,b)} @Post('non-conformities/:id/soumettre-validation') ncSoumettreValidation(@Param('id')id:string){return this.s.ncSoumettreValidation(id)} @Post('non-conformities/:id/approuver-validation') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) ncApprouverValidation(@Param('id')id:string,@Body()b:any){return this.s.ncApprouverValidation(id,b?.commentaire)} @Post('non-conformities/:id/rejeter-validation') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) ncRejeterValidation(@Param('id')id:string,@Body()b:any){return this.s.ncRejeterValidation(id,b?.commentaire)}
@Get('non-conformities/:id/containment-actions') ncContainmentActionList(@Param('id')id:string){return this.s.ncContainmentActionList(id)} @Post('nc-containment-actions') ncContainmentActionCreate(@Body()b:CreateNcContainmentActionDto){return this.s.ncContainmentActionCreate(b)} @Patch('nc-containment-actions/:id') ncContainmentActionUpdate(@Param('id')id:string,@Body()b:UpdateNcContainmentActionDto){return this.s.ncContainmentActionUpdate(id,b)} @Delete('nc-containment-actions/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) ncContainmentActionDelete(@Param('id')id:string){return this.s.ncContainmentActionDelete(id)}
@Get('non-conformities/:id/causes') ncCauseList(@Param('id')id:string){return this.s.ncCauseList(id)} @Post('nc-causes') ncCauseCreate(@Body()b:CreateNcCauseDto){return this.s.ncCauseCreate(b)} @Patch('nc-causes/:id') ncCauseUpdate(@Param('id')id:string,@Body()b:UpdateNcCauseDto){return this.s.ncCauseUpdate(id,b)} @Delete('nc-causes/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) ncCauseDelete(@Param('id')id:string){return this.s.ncCauseDelete(id)}
@Get('nc-recurrentes') ncRecurrentes(){return this.s.ncRecurrentes()} @Get('nc-alertes') ncAlertes(){return this.s.ncAlertes()} @Get('nc-trends') ncTrends(){return this.s.ncTrends()} @Get('nc-synthese-direction') ncSyntheseDirection(){return this.s.ncSyntheseDirection()}
@Get('non-conformities/:id/costs') ncCostList(@Param('id')id:string){return this.s.ncCostList(id)} @Post('nc-costs') ncCostCreate(@Body()b:CreateNcCostDto){return this.s.ncCostCreate(b)} @Patch('nc-costs/:id') ncCostUpdate(@Param('id')id:string,@Body()b:UpdateNcCostDto){return this.s.ncCostUpdate(id,b)} @Delete('nc-costs/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) ncCostDelete(@Param('id')id:string){return this.s.ncCostDelete(id)}
@Post('non-conformities/:id/generate-risk') nonConformityGenerateRisk(@Param('id')id:string){return this.s.nonConformityGenerateRisk(id)}
@Get('actions') actionList(@Query('status')status?:string,@Query('take')take?:string,@Query('skip')skip?:string){return this.s.actionList(status,take?Number(take):undefined,skip?Number(skip):undefined)} @Get('actions-search') actionSearch(@Query('q')q?:string){return this.s.actionSearch(q||'')} @Get('actions/:id') actionGet(@Param('id')id:string){return this.s.actionGet(id)} @Post('actions') actionCreate(@Body()b:CreateActionDto){return this.s.actionCreate(b)} @Patch('actions/:id') actionUpdate(@Param('id')id:string,@Body()b:UpdateActionDto){return this.s.actionUpdate(id,b)} @Delete('actions/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) actionDelete(@Param('id')id:string){return this.s.actionDelete(id)}
@Get('action-dashboard') actionDashboard(){return this.s.actionDashboard()}
@Get('actions/:id/causes') actionCauseList(@Param('id')id:string){return this.s.actionCauseList(id)} @Post('action-causes') actionCauseCreate(@Body()b:CreateActionCauseDto){return this.s.actionCauseCreate(b)} @Patch('action-causes/:id') actionCauseUpdate(@Param('id')id:string,@Body()b:UpdateActionCauseDto){return this.s.actionCauseUpdate(id,b)} @Delete('action-causes/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) actionCauseDelete(@Param('id')id:string){return this.s.actionCauseDelete(id)}
@Get('capa-links/by-source') capaLinksBySource(@Query('sourceModule')sourceModule:string,@Query('sourceEntityId')sourceEntityId:string){return this.s.capaLinksBySource(sourceModule,sourceEntityId)}
@Get('capa-links/duplicates') capaDetectDuplicates(@Query('sourceModule')sourceModule:string,@Query('sourceEntityId')sourceEntityId:string){return this.s.capaDetectDuplicates(sourceModule,sourceEntityId)}
@Get('capa-links/prefill') capaPrefillFromSource(@Query('sourceModule')sourceModule:string,@Query('sourceEntityId')sourceEntityId:string){return this.s.capaPrefillFromSource(sourceModule,sourceEntityId)}
@Post('capa-links/create-from-source') capaCreateFromSource(@Body()b:any){return this.s.capaCreateFromSource(b.sourceModule,b.sourceEntityId,b)}
@Post('capa-links/create-common') capaCreateCommon(@Body()b:any){return this.s.capaCreateCommon(b.sources,b)}
@Get('actions/:id/links') capaLinksByAction(@Param('id')id:string){return this.s.capaLinksByAction(id)} @Post('actions/:id/links') capaLinkAdd(@Param('id')id:string,@Body()b:any){return this.s.capaLinkAdd(id,b)} @Delete('capa-links/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) capaLinkDelete(@Param('id')id:string){return this.s.capaLinkDelete(id)}
@Post('actions/:id/effectiveness') actionEffectivenessCheck(@Param('id')id:string,@Body()b:any){return this.s.actionEffectivenessCheck(id,b)} @Post('actions/:id/close') actionClose(@Param('id')id:string,@Body()b:any){return this.s.actionClose(id,b)} @Post('actions/:id/reopen') actionReopen(@Param('id')id:string){return this.s.actionReopen(id)} @Post('actions/:id/soumettre-validation') actionSoumettreValidation(@Param('id')id:string){return this.s.actionSoumettreValidation(id)} @Post('actions/:id/approuver-validation') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) actionApprouverValidation(@Param('id')id:string,@Body()b:any){return this.s.actionApprouverValidation(id,b?.commentaire)} @Post('actions/:id/rejeter-validation') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) actionRejeterValidation(@Param('id')id:string,@Body()b:any){return this.s.actionRejeterValidation(id,b?.commentaire)}
@Get('actions/:id/extensions') actionExtensionList(@Param('id')id:string){return this.s.actionExtensionList(id)} @Post('actions/:id/extensions') actionExtensionCreate(@Param('id')id:string,@Body()b:CreateActionExtensionDto){return this.s.actionExtensionCreate(id,b)}
@Get('action-alertes') actionAlertes(){return this.s.actionAlertes()} @Get('action-performance-score') actionPerformanceScore(){return this.s.actionPerformanceScore()} @Get('action-trends') actionTrends(){return this.s.actionTrends()}
@Get('risks') riskList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.riskList(take?Number(take):undefined,skip?Number(skip):undefined)} @Get('risks-search') riskSearch(@Query('q')q?:string){return this.s.riskSearch(q||'')} @Get('risks/:id') riskGet(@Param('id')id:string){return this.s.riskGet(id)} @Post('risks') riskCreate(@Body()b:CreateRiskDto){return this.s.riskCreate(b)} @Patch('risks/:id') riskUpdate(@Param('id')id:string,@Body()b:UpdateRiskDto){return this.s.riskUpdate(id,b)} @Delete('risks/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) riskDelete(@Param('id')id:string){return this.s.riskDelete(id)}
@Post('risks/:id/reevaluate') riskReevaluate(@Param('id')id:string,@Body()b:any){return this.s.riskReevaluate(id,b)} @Post('risks/:id/soumettre-validation') riskSoumettreValidation(@Param('id')id:string){return this.s.riskSoumettreValidation(id)} @Post('risks/:id/approuver-validation') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) riskApprouverValidation(@Param('id')id:string,@Body()b:any){return this.s.riskApprouverValidation(id,b?.commentaire)} @Post('risks/:id/rejeter-validation') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) riskRejeterValidation(@Param('id')id:string,@Body()b:any){return this.s.riskRejeterValidation(id,b?.commentaire)}
@Get('risk-dashboard') riskDashboard(){return this.s.riskDashboard()} @Get('risk-matrice') riskMatrice(){return this.s.riskMatrice()} @Get('risk-top10') riskTop10(){return this.s.riskTop10()} @Get('risk-alertes') riskAlertes(){return this.s.riskAlertes()}
@Get('risk-categories') riskCategoryList(){return this.s.riskCategoryList()} @Post('risk-categories') riskCategoryCreate(@Body()b:any){return this.s.riskCategoryCreate(b)} @Patch('risk-categories/:id') riskCategoryUpdate(@Param('id')id:string,@Body()b:any){return this.s.riskCategoryUpdate(id,b)} @Delete('risk-categories/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) riskCategoryDelete(@Param('id')id:string,@Query('force')force?:string){return this.s.riskCategoryDelete(id,force==='true')}
@Get('work-units') workUnitList(@Query('siteId')siteId?:string){return this.s.workUnitList(siteId)} @Post('work-units') workUnitCreate(@Body()b:any){return this.s.workUnitCreate(b)} @Patch('work-units/:id') workUnitUpdate(@Param('id')id:string,@Body()b:any){return this.s.workUnitUpdate(id,b)} @Delete('work-units/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) workUnitDelete(@Param('id')id:string){return this.s.workUnitDelete(id)}
@Get('risks/:id/measures') riskMeasureList(@Param('id')id:string){return this.s.riskMeasureList(id)} @Post('risk-measures') riskMeasureCreate(@Body()b:CreateRiskMeasureDto){return this.s.riskMeasureCreate(b)} @Patch('risk-measures/:id') riskMeasureUpdate(@Param('id')id:string,@Body()b:UpdateRiskMeasureDto){return this.s.riskMeasureUpdate(id,b)} @Delete('risk-measures/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) riskMeasureDelete(@Param('id')id:string){return this.s.riskMeasureDelete(id)}
@Get('risk-settings') riskSettingsGet(){return this.s.riskSettingsGet()} @Patch('risk-settings') riskSettingsUpdate(@Body()b:any){return this.s.riskSettingsUpdate(b)}
@Get('audits') auditList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.auditList(take?Number(take):undefined,skip?Number(skip):undefined)} @Get('audits-search') auditSearch(@Query('q')q?:string){return this.s.auditSearch(q||'')} @Get('audits/:id') auditGet(@Param('id')id:string){return this.s.auditGet(id)} @Get('audit-dashboard') auditDashboard(){return this.s.auditDashboard()} @Post('audits') auditCreate(@Body()b:CreateAuditDto){return this.s.auditCreate(b)} @Patch('audits/:id') auditUpdate(@Param('id')id:string,@Body()b:UpdateAuditDto){return this.s.auditUpdate(id,b)} @Delete('audits/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditDelete(@Param('id')id:string){return this.s.auditDelete(id)}
@Post('audits/:id/findings') auditFindingCreate(@Param('id')id:string,@Body()b:CreateAuditFindingDto){return this.s.auditFindingCreate(id,b)} @Patch('audit-findings/:id') auditFindingUpdate(@Param('id')id:string,@Body()b:UpdateAuditFindingDto){return this.s.auditFindingUpdate(id,b)} @Delete('audit-findings/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditFindingDelete(@Param('id')id:string){return this.s.auditFindingDelete(id)} @Post('audit-findings/:id/generate-nc') auditFindingGenerateNc(@Param('id')id:string){return this.s.auditFindingGenerateNc(id)} @Post('audit-findings/:id/generate-risk') auditFindingGenerateRisk(@Param('id')id:string){return this.s.auditFindingGenerateRisk(id)} @Post('audit-findings/:id/generate-action') auditFindingGenerateAction(@Param('id')id:string,@Body()b:any){return this.s.auditFindingGenerateAction(id,b)}
@Get('audit-types') auditTypeList(){return this.s.auditTypeList()} @Post('audit-types') auditTypeCreate(@Body()b:any){return this.s.auditTypeCreate(b)} @Patch('audit-types/:id') auditTypeUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditTypeUpdate(id,b)} @Delete('audit-types/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditTypeDelete(@Param('id')id:string){return this.s.auditTypeDelete(id)}
@Get('audit-referentials') auditReferentialList(){return this.s.auditReferentialList()} @Post('audit-referentials') auditReferentialCreate(@Body()b:any){return this.s.auditReferentialCreate(b)} @Patch('audit-referentials/:id') auditReferentialUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditReferentialUpdate(id,b)} @Delete('audit-referentials/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditReferentialDelete(@Param('id')id:string){return this.s.auditReferentialDelete(id)}
@Post('audit-referential-items') auditReferentialItemCreate(@Body()b:any){return this.s.auditReferentialItemCreate(b)} @Patch('audit-referential-items/:id') auditReferentialItemUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditReferentialItemUpdate(id,b)} @Delete('audit-referential-items/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditReferentialItemDelete(@Param('id')id:string){return this.s.auditReferentialItemDelete(id)}
@Get('audit-programs') auditProgramList(){return this.s.auditProgramList()} @Post('audit-programs') auditProgramCreate(@Body()b:any){return this.s.auditProgramCreate(b)} @Patch('audit-programs/:id') auditProgramUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditProgramUpdate(id,b)} @Delete('audit-programs/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditProgramDelete(@Param('id')id:string){return this.s.auditProgramDelete(id)} @Post('audit-programs/:id/generate-audit') auditProgramGenerateAudit(@Param('id')id:string){return this.s.auditProgramGenerateAudit(id)}
@Get('audit-checklists') auditChecklistList(){return this.s.auditChecklistList()} @Post('audit-checklists') auditChecklistCreate(@Body()b:any){return this.s.auditChecklistCreate(b)} @Patch('audit-checklists/:id') auditChecklistUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditChecklistUpdate(id,b)} @Delete('audit-checklists/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditChecklistDelete(@Param('id')id:string){return this.s.auditChecklistDelete(id)}
@Post('audit-checklist-items') auditChecklistItemCreate(@Body()b:any){return this.s.auditChecklistItemCreate(b)} @Patch('audit-checklist-items/:id') auditChecklistItemUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditChecklistItemUpdate(id,b)} @Delete('audit-checklist-items/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditChecklistItemDelete(@Param('id')id:string){return this.s.auditChecklistItemDelete(id)}
@Post('audits/:auditId/responses/:checklistItemId') auditResponseSave(@Param('auditId')auditId:string,@Param('checklistItemId')checklistItemId:string,@Body()b:any){return this.s.auditResponseSave(auditId,checklistItemId,b)}
@Get('auditeurs') auditeursList(){return this.s.auditeursList()} @Patch('auditeurs/:userId/profile') auditorProfileUpsert(@Param('userId')userId:string,@Body()b:any){return this.s.auditorProfileUpsert(userId,b)}
@Post('audits/:id/signatures') auditSignatureCreate(@Param('id')id:string,@Body()b:any){return this.s.auditSignatureCreate(id,b)} @Post('audit-signatures/:id/sign') auditSignatureSign(@Param('id')id:string,@Body()b:{signataireId:string}){return this.s.auditSignatureSign(id,b.signataireId)} @Delete('audit-signatures/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) auditSignatureDelete(@Param('id')id:string){return this.s.auditSignatureDelete(id)}
@Get('audit-trends') auditTrends(){return this.s.auditTrends()} @Get('audit-nc-recurrentes') auditNcRecurrentes(){return this.s.auditNcRecurrentes()} @Get('audit-synthese-direction') auditSyntheseDirection(){return this.s.auditSyntheseDirection()}
@Get('audit-comparaison') auditComparaison(@Query('debut1')debut1:string,@Query('fin1')fin1:string,@Query('debut2')debut2:string,@Query('fin2')fin2:string){return this.s.auditComparaison(debut1,fin1,debut2,fin2)}
@Get('environment') envList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.envList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('environment') envCreate(@Body()b:any){return this.s.envCreate(b)} @Patch('environment/:id') envUpdate(@Param('id')id:string,@Body()b:any){return this.s.envUpdate(id,b)} @Delete('environment/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) envDelete(@Param('id')id:string){return this.s.envDelete(id)}
@Get('environnement-aspects') environnementAspectList(){return this.s.environnementAspectList()} @Get('environnement-aspects/:id') environnementAspectGet(@Param('id')id:string){return this.s.environnementAspectGet(id)} @Post('environnement-aspects') environnementAspectCreate(@Body()b:any){return this.s.environnementAspectCreate(b)} @Patch('environnement-aspects/:id') environnementAspectUpdate(@Param('id')id:string,@Body()b:any){return this.s.environnementAspectUpdate(id,b)} @Delete('environnement-aspects/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) environnementAspectDelete(@Param('id')id:string){return this.s.environnementAspectDelete(id)} @Post('environnement-aspects/:id/generate-risk') environnementAspectGenerateRisk(@Param('id')id:string){return this.s.environnementAspectGenerateRisk(id)}
@Get('environnement-dashboard') environnementDashboard(){return this.s.environnementDashboard()} @Get('environnement-alertes') environnementAlertes(){return this.s.environnementAlertes()} @Get('environnement-tendances') environnementTendances(){return this.s.environnementTendances()}
@Get('produits-chimiques') produitChimiqueList(){return this.s.produitChimiqueList()} @Post('produits-chimiques') produitChimiqueCreate(@Body()b:any){return this.s.produitChimiqueCreate(b)} @Patch('produits-chimiques/:id') produitChimiqueUpdate(@Param('id')id:string,@Body()b:any){return this.s.produitChimiqueUpdate(id,b)} @Delete('produits-chimiques/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) produitChimiqueDelete(@Param('id')id:string){return this.s.produitChimiqueDelete(id)}
@Get('trainings') trainingList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.trainingList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('trainings') trainingCreate(@Body()b:any){return this.s.trainingCreate(b)} @Patch('trainings/:id') trainingUpdate(@Param('id')id:string,@Body()b:any){return this.s.trainingUpdate(id,b)} @Delete('trainings/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) trainingDelete(@Param('id')id:string){return this.s.trainingDelete(id)}
@Get('trainings/:id') trainingGet(@Param('id')id:string){return this.s.trainingGet(id)} @Patch('trainings/:id/participants') trainingParticipantsSet(@Param('id')id:string,@Body()b:any){return this.s.trainingParticipantsSet(id,b.participants||[])}
@Get('training-categories') trainingCategoryList(){return this.s.trainingCategoryList()} @Post('training-categories') trainingCategoryCreate(@Body()b:any){return this.s.trainingCategoryCreate(b)} @Patch('training-categories/:id') trainingCategoryUpdate(@Param('id')id:string,@Body()b:any){return this.s.trainingCategoryUpdate(id,b)} @Delete('training-categories/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) trainingCategoryDelete(@Param('id')id:string,@Query('force')force?:string){return this.s.trainingCategoryDelete(id,force==='true')}
@Get('training-settings') trainingSettingsGet(){return this.s.trainingSettingsGet()} @Patch('training-settings') trainingSettingsUpdate(@Body()b:any){return this.s.trainingSettingsUpdate(b)}
@Get('formation-dashboard') formationDashboard(){return this.s.formationDashboard()}
@Get('habilitations') habilitationList(){return this.s.habilitationList()} @Get('habilitations/:id') habilitationGet(@Param('id')id:string){return this.s.habilitationGet(id)} @Post('habilitations') habilitationCreate(@Body()b:any){return this.s.habilitationCreate(b)} @Patch('habilitations/:id') habilitationUpdate(@Param('id')id:string,@Body()b:any){return this.s.habilitationUpdate(id,b)} @Delete('habilitations/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) habilitationDelete(@Param('id')id:string){return this.s.habilitationDelete(id)}
@Get('habilitation-categories') habilitationCategoryList(){return this.s.habilitationCategoryList()} @Post('habilitation-categories') habilitationCategoryCreate(@Body()b:any){return this.s.habilitationCategoryCreate(b)} @Patch('habilitation-categories/:id') habilitationCategoryUpdate(@Param('id')id:string,@Body()b:any){return this.s.habilitationCategoryUpdate(id,b)} @Delete('habilitation-categories/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) habilitationCategoryDelete(@Param('id')id:string,@Query('force')force?:string){return this.s.habilitationCategoryDelete(id,force==='true')}
@Get('competence-niveaux') competenceNiveauList(){return this.s.competenceNiveauList()} @Post('competence-niveaux') competenceNiveauCreate(@Body()b:any){return this.s.competenceNiveauCreate(b)} @Patch('competence-niveaux/:id') competenceNiveauUpdate(@Param('id')id:string,@Body()b:any){return this.s.competenceNiveauUpdate(id,b)} @Delete('competence-niveaux/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) competenceNiveauDelete(@Param('id')id:string){return this.s.competenceNiveauDelete(id)}
@Get('competences') competenceList(){return this.s.competenceList()} @Post('competences') competenceCreate(@Body()b:any){return this.s.competenceCreate(b)} @Patch('competences/:id') competenceUpdate(@Param('id')id:string,@Body()b:any){return this.s.competenceUpdate(id,b)} @Delete('competences/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) competenceDelete(@Param('id')id:string){return this.s.competenceDelete(id)}
@Get('employee-competences') employeeCompetenceList(){return this.s.employeeCompetenceList()} @Post('employee-competences') employeeCompetenceUpsert(@Body()b:any){return this.s.employeeCompetenceUpsert(b)} @Delete('employee-competences/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) employeeCompetenceDelete(@Param('id')id:string){return this.s.employeeCompetenceDelete(id)}
@Get('competence-matrice') competenceMatrice(){return this.s.competenceMatrice()}
@Get('besoins-formation') besoinFormationList(){return this.s.besoinFormationList()} @Patch('besoins-formation/:id') besoinFormationUpdate(@Param('id')id:string,@Body()b:any){return this.s.besoinFormationUpdate(id,b)} @Post('besoins-formation/:id/transformer') besoinFormationTransformer(@Param('id')id:string,@Body()b:any){return this.s.besoinFormationTransformer(id,b)}
@Post('besoins-formation-detecter') detecterBesoinsFormation(){return this.s.detecterBesoinsFormation()}
@Get('efficacite-evaluations') efficaciteEvaluationList(){return this.s.efficaciteEvaluationList()} @Post('efficacite-evaluations') efficaciteEvaluationCreate(@Body()b:any){return this.s.efficaciteEvaluationCreate(b)} @Patch('efficacite-evaluations/:id') efficaciteEvaluationUpdate(@Param('id')id:string,@Body()b:any){return this.s.efficaciteEvaluationUpdate(id,b)} @Delete('efficacite-evaluations/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) efficaciteEvaluationDelete(@Param('id')id:string){return this.s.efficaciteEvaluationDelete(id)}
@Get('formations-a-evaluer-efficacite') formationsAEvaluerEfficacite(){return this.s.formationsAEvaluerEfficacite()}
@Get('formation-budget-detail') formationBudgetDetail(){return this.s.formationBudgetDetail()}
@Get('accueil-securite-stats') accueilSecuriteStats(){return this.s.accueilSecuriteStats()}
@Get('equipment') equipmentList(@Query('siteId')siteId?:string,@Query('take')take?:string,@Query('skip')skip?:string){return this.s.equipmentList(siteId,take?Number(take):undefined,skip?Number(skip):undefined)} @Post('equipment') equipmentCreate(@Body()b:any){return this.s.equipmentCreate(b)} @Patch('equipment/:id') equipmentUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentUpdate(id,b)} @Delete('equipment/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentDelete(@Param('id')id:string){return this.s.equipmentDelete(id)}
@Get('equipment-dashboard') equipmentDashboard(){return this.s.equipmentDashboard()}
@Get('equipment/qr/:token') equipmentByQrToken(@Param('token')token:string){return this.s.equipmentByQrToken(token)}
@Post('equipment/:id/regenerate-qr') equipmentRegenerateQr(@Param('id')id:string){return this.s.regenerateEquipmentQr(id)}
@Get('equipment/:id') equipmentGet(@Param('id')id:string){return this.s.equipmentGet(id)}
@Post('equipment/:id/generate-risk') equipmentGenerateRisk(@Param('id')id:string,@Body()b:any){return this.s.equipmentGenerateRisk(id,b)}
@Post('equipment/:id/generate-nc') equipmentGenerateNc(@Param('id')id:string,@Body()b:any){return this.s.equipmentGenerateNc(id,b)}
@Post('equipment/:id/generate-action') equipmentGenerateAction(@Param('id')id:string,@Body()b:any){return this.s.equipmentGenerateAction(id,b)}
@Get('equipment-categories') equipmentCategoryList(){return this.s.equipmentCategoryList()} @Post('equipment-categories') equipmentCategoryCreate(@Body()b:any){return this.s.equipmentCategoryCreate(b)} @Patch('equipment-categories/:id') equipmentCategoryUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentCategoryUpdate(id,b)} @Delete('equipment-categories/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentCategoryDelete(@Param('id')id:string,@Query('force')force?:string){return this.s.equipmentCategoryDelete(id,force==='true')}
@Get('equipment-settings') equipmentSettingsGet(){return this.s.equipmentSettingsGet()} @Patch('equipment-settings') equipmentSettingsUpdate(@Body()b:any){return this.s.equipmentSettingsUpdate(b)}
@Get('equipment-maintenance-plans') equipmentMaintenancePlanList(@Query('equipmentId')equipmentId?:string){return this.s.equipmentMaintenancePlanList(equipmentId)} @Post('equipment-maintenance-plans') equipmentMaintenancePlanCreate(@Body()b:any){return this.s.equipmentMaintenancePlanCreate(b)} @Patch('equipment-maintenance-plans/:id') equipmentMaintenancePlanUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentMaintenancePlanUpdate(id,b)} @Delete('equipment-maintenance-plans/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentMaintenancePlanDelete(@Param('id')id:string){return this.s.equipmentMaintenancePlanDelete(id)}
@Get('equipment-maintenance-records') equipmentMaintenanceRecordList(@Query('equipmentId')equipmentId?:string){return this.s.equipmentMaintenanceRecordList(equipmentId)} @Post('equipment-maintenance-records') equipmentMaintenanceRecordCreate(@Body()b:any){return this.s.equipmentMaintenanceRecordCreate(b)} @Patch('equipment-maintenance-records/:id') equipmentMaintenanceRecordUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentMaintenanceRecordUpdate(id,b)} @Delete('equipment-maintenance-records/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentMaintenanceRecordDelete(@Param('id')id:string){return this.s.equipmentMaintenanceRecordDelete(id)}
@Get('equipment/:id/maintenance-stats') equipmentMaintenanceStats(@Param('id')id:string){return this.s.equipmentMaintenanceStats(id)}
@Get('equipment-controls') equipmentControlList(@Query('equipmentId')equipmentId?:string){return this.s.equipmentControlList(equipmentId)} @Post('equipment-controls') equipmentControlCreate(@Body()b:any){return this.s.equipmentControlCreate(b)} @Patch('equipment-controls/:id') equipmentControlUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentControlUpdate(id,b)} @Delete('equipment-controls/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentControlDelete(@Param('id')id:string){return this.s.equipmentControlDelete(id)}
@Post('equipment-controls/:id/generate-nc') equipmentControlGenerateNc(@Param('id')id:string,@Body()b:any){return this.s.equipmentControlGenerateNc(id,b)}
@Get('equipment-calibrations') equipmentCalibrationList(@Query('equipmentId')equipmentId?:string){return this.s.equipmentCalibrationList(equipmentId)} @Post('equipment-calibrations') equipmentCalibrationCreate(@Body()b:any){return this.s.equipmentCalibrationCreate(b)} @Patch('equipment-calibrations/:id') equipmentCalibrationUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentCalibrationUpdate(id,b)} @Delete('equipment-calibrations/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentCalibrationDelete(@Param('id')id:string){return this.s.equipmentCalibrationDelete(id)}
@Post('equipment-calibrations/:id/generate-nc') equipmentCalibrationGenerateNc(@Param('id')id:string,@Body()b:any){return this.s.equipmentCalibrationGenerateNc(id,b)}
@Get('equipment-inspections') equipmentInspectionList(@Query('equipmentId')equipmentId?:string){return this.s.equipmentInspectionList(equipmentId)} @Post('equipment-inspections') equipmentInspectionCreate(@Body()b:any){return this.s.equipmentInspectionCreate(b)} @Patch('equipment-inspections/:id') equipmentInspectionUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentInspectionUpdate(id,b)} @Delete('equipment-inspections/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentInspectionDelete(@Param('id')id:string){return this.s.equipmentInspectionDelete(id)}
@Get('equipment-consignations') equipmentConsignationList(@Query('equipmentId')equipmentId?:string){return this.s.equipmentConsignationList(equipmentId)} @Post('equipment-consignations') equipmentConsignationCreate(@Body()b:any){return this.s.equipmentConsignationCreate(b)} @Post('equipment-consignations/:id/lever') equipmentConsignationLever(@Param('id')id:string,@Body()b:any){return this.s.equipmentConsignationLever(id,b)} @Delete('equipment-consignations/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) equipmentConsignationDelete(@Param('id')id:string){return this.s.equipmentConsignationDelete(id)}
@Get('safety-events') events(@Query('take')take?:string,@Query('skip')skip?:string,@Query('siteId')siteId?:string){return this.s.events(take?Number(take):undefined,skip?Number(skip):undefined,siteId)} @Get('safety-events-stats') safetyEventsStats(){return this.s.safetyEventsStats()} @Get('safety-events-alertes') safetyEventsAlertes(){return this.s.safetyEventsAlertes()} @Get('safety-events-recidives') safetyEventsRecidives(){return this.s.safetyEventsRecidives()} @Get('safety-events/:id') eventGet(@Param('id')id:string){return this.s.eventGet(id)} @Post('safety-events') eventCreate(@Body()b:any){return this.s.eventCreate(b)} @Patch('safety-events/:id') eventUpdate(@Param('id')id:string,@Body()b:any){return this.s.eventUpdate(id,b)} @Delete('safety-events/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) eventDelete(@Param('id')id:string){return this.s.eventDelete(id)}
@Post('safety-events/:id/generate-risk') safetyEventGenerateRisk(@Param('id')id:string){return this.s.safetyEventGenerateRisk(id)}
@Get('processus') processusList(@Query('siteId')siteId?:string){return this.s.processusList(siteId)} @Get('processus/:id') processusGet(@Param('id')id:string){return this.s.processusGet(id)} @Post('processus') processusCreate(@Body()b:any){return this.s.processusCreate(b)} @Patch('processus/:id') processusUpdate(@Param('id')id:string,@Body()b:any){return this.s.processusUpdate(id,b)} @Delete('processus/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) processusDelete(@Param('id')id:string){return this.s.processusDelete(id)}
@Get('processus/:id/activities') processusActivityList(@Param('id')id:string){return this.s.processusActivityList(id)} @Post('processus-activities') processusActivityCreate(@Body()b:any){return this.s.processusActivityCreate(b)} @Patch('processus-activities/:id') processusActivityUpdate(@Param('id')id:string,@Body()b:any){return this.s.processusActivityUpdate(id,b)} @Delete('processus-activities/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) processusActivityDelete(@Param('id')id:string){return this.s.processusActivityDelete(id)}
@Post('processus-activities/:id/raci') processusRaciUpsert(@Param('id')id:string,@Body()b:any){return this.s.processusRaciUpsert(id,b)} @Delete('processus-raci/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) processusRaciDelete(@Param('id')id:string){return this.s.processusRaciDelete(id)}
@Get('processus/:id/exigences') processusExigenceList(@Param('id')id:string){return this.s.processusExigenceList(id)} @Post('processus-exigences') processusExigenceCreate(@Body()b:any){return this.s.processusExigenceCreate(b)} @Patch('processus-exigences/:id') processusExigenceUpdate(@Param('id')id:string,@Body()b:any){return this.s.processusExigenceUpdate(id,b)} @Delete('processus-exigences/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) processusExigenceDelete(@Param('id')id:string){return this.s.processusExigenceDelete(id)}
@Get('processus-links') processusLinkList(){return this.s.processusLinkList()} @Post('processus-links') processusLinkCreate(@Body()b:any){return this.s.processusLinkCreate(b)} @Delete('processus-links/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) processusLinkDelete(@Param('id')id:string){return this.s.processusLinkDelete(id)}
@Get('indicateurs-qualite') indicateurList(@Query('domaine')domaine?:string){return this.s.indicateurList(domaine)} @Post('indicateurs-qualite') indicateurCreate(@Body()b:any){return this.s.indicateurCreate(b)} @Patch('indicateurs-qualite/:id') indicateurUpdate(@Param('id')id:string,@Body()b:any){return this.s.indicateurUpdate(id,b)} @Delete('indicateurs-qualite/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) indicateurDelete(@Param('id')id:string){return this.s.indicateurDelete(id)}
@Get('indicateurs-qualite/:id/mesures') indicateurMesureList(@Param('id')id:string){return this.s.indicateurMesureList(id)} @Post('indicateurs-qualite/:id/mesures') indicateurMesureCreate(@Param('id')id:string,@Body()b:any){return this.s.indicateurMesureCreate(id,b)}
@Get('indicateurs-auto') indicateursAuto(){return this.s.indicateursAuto()}
@Get('indicateurs-auto-compare') indicateursAutoCompare(){return this.s.indicateursAutoCompare()}
@Get('indicateurs-ponderation') indicateurPonderationList(){return this.s.indicateurPonderationList()} @Post('indicateurs-ponderation') indicateurPonderationSet(@Body()b:any){return this.s.indicateurPonderationSet(b.autoKey,Number(b.poids))}
@Get('indice-global-qualite') indiceGlobalQualite(){return this.s.indiceGlobalQualite()}
@Get('reclamations') reclamationList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.reclamationList(take?Number(take):undefined,skip?Number(skip):undefined)} @Get('reclamations-stats') reclamationsStats(){return this.s.reclamationsStats()} @Get('reclamations-alertes') reclamationsAlertes(){return this.s.reclamationsAlertes()} @Get('reclamations-score') reclamationsScoreGlobal(){return this.s.reclamationsScoreGlobal()} @Get('reclamations/:id') reclamationGet(@Param('id')id:string){return this.s.reclamationGet(id)} @Post('reclamations') reclamationCreate(@Body()b:any){return this.s.reclamationCreate(b)} @Patch('reclamations/:id') reclamationUpdate(@Param('id')id:string,@Body()b:any){return this.s.reclamationUpdate(id,b)} @Delete('reclamations/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) reclamationDelete(@Param('id')id:string){return this.s.reclamationDelete(id)}
@Get('fournisseurs') fournisseurList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.fournisseurList(take?Number(take):undefined,skip?Number(skip):undefined)} @Get('fournisseurs-classement') fournisseursClassement(){return this.s.fournisseursClassement()} @Get('fournisseurs-alertes') fournisseursAlertes(){return this.s.fournisseursAlertes()} @Get('fournisseurs-matrice-risque') fournisseursMatriceRisque(){return this.s.fournisseursMatriceRisque()} @Get('fournisseurs/:id') fournisseurGet(@Param('id')id:string){return this.s.fournisseurGet(id)} @Get('fournisseurs/:id/score') fournisseurScoreGlobal(@Param('id')id:string){return this.s.fournisseurScoreGlobal(id)} @Post('fournisseurs') fournisseurCreate(@Body()b:any){return this.s.fournisseurCreate(b)} @Patch('fournisseurs/:id') fournisseurUpdate(@Param('id')id:string,@Body()b:any){return this.s.fournisseurUpdate(id,b)} @Delete('fournisseurs/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) fournisseurDelete(@Param('id')id:string){return this.s.fournisseurDelete(id)}
@Get('fournisseurs/:id/certifications') fournisseurCertificationList(@Param('id')id:string){return this.s.fournisseurCertificationList(id)} @Post('fournisseur-certifications') fournisseurCertificationCreate(@Body()b:any){return this.s.fournisseurCertificationCreate(b)} @Patch('fournisseur-certifications/:id') fournisseurCertificationUpdate(@Param('id')id:string,@Body()b:any){return this.s.fournisseurCertificationUpdate(id,b)} @Delete('fournisseur-certifications/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) fournisseurCertificationDelete(@Param('id')id:string){return this.s.fournisseurCertificationDelete(id)}
@Get('visites-medicales') visiteMedicaleList(){return this.s.visiteMedicaleList()} @Post('visites-medicales') visiteMedicaleCreate(@Body()b:any){return this.s.visiteMedicaleCreate(b)} @Patch('visites-medicales/:id') visiteMedicaleUpdate(@Param('id')id:string,@Body()b:any){return this.s.visiteMedicaleUpdate(id,b)} @Delete('visites-medicales/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) visiteMedicaleDelete(@Param('id')id:string){return this.s.visiteMedicaleDelete(id)}
@Get('risques-sanitaires') risqueSanitaireList(){return this.s.risqueSanitaireList()} @Get('risques-sanitaires/:id') risqueSanitaireGet(@Param('id')id:string){return this.s.risqueSanitaireGet(id)} @Post('risques-sanitaires') risqueSanitaireCreate(@Body()b:any){return this.s.risqueSanitaireCreate(b)} @Patch('risques-sanitaires/:id') risqueSanitaireUpdate(@Param('id')id:string,@Body()b:any){return this.s.risqueSanitaireUpdate(id,b)} @Delete('risques-sanitaires/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) risqueSanitaireDelete(@Param('id')id:string){return this.s.risqueSanitaireDelete(id)}
@Post('expositions') expositionCreate(@Body()b:any){return this.s.expositionCreate(b)} @Delete('expositions/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) expositionDelete(@Param('id')id:string){return this.s.expositionDelete(id)}
@Get('analyses-ergonomiques') analyseErgonomiqueList(){return this.s.analyseErgonomiqueList()} @Get('analyses-ergonomiques/:id') analyseErgonomiqueGet(@Param('id')id:string){return this.s.analyseErgonomiqueGet(id)} @Post('analyses-ergonomiques') analyseErgonomiqueCreate(@Body()b:any){return this.s.analyseErgonomiqueCreate(b)} @Patch('analyses-ergonomiques/:id') analyseErgonomiqueUpdate(@Param('id')id:string,@Body()b:any){return this.s.analyseErgonomiqueUpdate(id,b)} @Delete('analyses-ergonomiques/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) analyseErgonomiqueDelete(@Param('id')id:string){return this.s.analyseErgonomiqueDelete(id)}
@Get('tms-signalements') tmsSignalementList(){return this.s.tmsSignalementList()} @Post('tms-signalements') tmsSignalementCreate(@Body()b:any){return this.s.tmsSignalementCreate(b)} @Patch('tms-signalements/:id') tmsSignalementUpdate(@Param('id')id:string,@Body()b:any){return this.s.tmsSignalementUpdate(id,b)} @Delete('tms-signalements/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) tmsSignalementDelete(@Param('id')id:string){return this.s.tmsSignalementDelete(id)}
@Get('penibilite-facteurs') penibiliteFactorList(){return this.s.penibiliteFactorList()} @Post('penibilite-facteurs') penibiliteFactorCreate(@Body()b:any){return this.s.penibiliteFactorCreate(b)} @Delete('penibilite-facteurs/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) penibiliteFactorDelete(@Param('id')id:string){return this.s.penibiliteFactorDelete(id)}
@Get('penibilite-expositions') penibiliteExpositionList(){return this.s.penibiliteExpositionList()} @Post('penibilite-expositions') penibiliteExpositionCreate(@Body()b:any){return this.s.penibiliteExpositionCreate(b)} @Delete('penibilite-expositions/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) penibiliteExpositionDelete(@Param('id')id:string){return this.s.penibiliteExpositionDelete(id)}
@Get('hygiene-alertes') hygieneAlertes(){return this.s.hygieneAlertes()} @Get('hygiene-indice-global') hygieneIndiceGlobal(){return this.s.hygieneIndiceGlobal()}
@Get('veille-reglementaire') veilleList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.veilleList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('veille-reglementaire') veilleCreate(@Body()b:any){return this.s.veilleCreate(b)} @Patch('veille-reglementaire/:id') veilleUpdate(@Param('id')id:string,@Body()b:any){return this.s.veilleUpdate(id,b)} @Delete('veille-reglementaire/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) veilleDelete(@Param('id')id:string){return this.s.veilleDelete(id)}
@Get('regulatory-domains') regulatoryDomainList(){return this.s.regulatoryDomainList()} @Post('regulatory-domains') regulatoryDomainCreate(@Body()b:any){return this.s.regulatoryDomainCreate(b)} @Patch('regulatory-domains/:id') regulatoryDomainUpdate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryDomainUpdate(id,b)} @Delete('regulatory-domains/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) regulatoryDomainDelete(@Param('id')id:string){return this.s.regulatoryDomainDelete(id)}
@Get('regulatory-settings') regulatorySettingsGet(){return this.s.regulatorySettingsGet()} @Patch('regulatory-settings') regulatorySettingsUpdate(@Body()b:any){return this.s.regulatorySettingsUpdate(b)} @Get('organisation-settings') organisationSettingsGet(){return this.s.organisationSettingsGet()} @Patch('organisation-settings') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) organisationSettingsUpdate(@Body()b:any){return this.s.organisationSettingsUpdate(b)}
@Get('regulatory-texts') regulatoryTextList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.regulatoryTextList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('regulatory-texts') regulatoryTextCreate(@Body()b:any){return this.s.regulatoryTextCreate(b)} @Get('regulatory-texts/:id') regulatoryTextGet(@Param('id')id:string){return this.s.regulatoryTextGet(id)} @Patch('regulatory-texts/:id') regulatoryTextUpdate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryTextUpdate(id,b)} @Delete('regulatory-texts/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) regulatoryTextDelete(@Param('id')id:string){return this.s.regulatoryTextDelete(id)}
@Get('regulatory-requirements-dashboard') regulatoryDashboard(){return this.s.regulatoryDashboard()}
@Get('regulatory-alerts') regulatoryAlerts(){return this.s.regulatoryAlerts()}
@Get('regulatory-calendar') regulatoryCalendar(@Query('from')from?:string,@Query('to')to?:string){return this.s.regulatoryCalendar(from,to)}
@Get('regulatory-texts/:id/impact-analysis') regulatoryImpactAnalysis(@Param('id')id:string){return this.s.regulatoryImpactAnalysis(id)}
@Get('regulatory-risk-reevaluations') regulatoryRiskReevaluationList(@Query('requirementId')requirementId?:string){return this.s.regulatoryRiskReevaluationList(requirementId)}
@Post('regulatory-requirements/:id/request-risk-reevaluation') regulatoryRequestRiskReevaluation(@Param('id')id:string,@Body()b:any){return this.s.regulatoryRequestRiskReevaluation(id,b)}
@Patch('regulatory-risk-reevaluations/:id') regulatoryRiskReevaluationUpdate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryRiskReevaluationUpdate(id,b)}
@Post('risk-reevaluations-detecter') detecterReevaluationsRisquesCroisees(){return this.s.detecterReevaluationsRisquesCroisees()}
@Get('regulatory-requirements') regulatoryRequirementList(@Query('textId')textId?:string,@Query('domainId')domainId?:string,@Query('siteId')siteId?:string,@Query('applicabilite')applicabilite?:string,@Query('statutConformite')statutConformite?:string,@Query('take')take?:string,@Query('skip')skip?:string){return this.s.regulatoryRequirementList({textId,domainId,siteId,applicabilite,statutConformite},take?Number(take):undefined,skip?Number(skip):undefined)}
@Post('regulatory-requirements') regulatoryRequirementCreate(@Body()b:any){return this.s.regulatoryRequirementCreate(b)}
@Get('regulatory-requirements/:id') regulatoryRequirementGet(@Param('id')id:string){return this.s.regulatoryRequirementGet(id)}
@Patch('regulatory-requirements/:id') regulatoryRequirementUpdate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryRequirementUpdate(id,b)}
@Delete('regulatory-requirements/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) regulatoryRequirementDelete(@Param('id')id:string){return this.s.regulatoryRequirementDelete(id)}
@Post('regulatory-requirements/:id/applicability') regulatoryRequirementSetApplicabilite(@Param('id')id:string,@Body()b:any){return this.s.regulatoryRequirementSetApplicabilite(id,b)}
@Post('regulatory-requirements/:id/evaluations') regulatoryEvaluationCreate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryEvaluationCreate(id,b)}
@Get('regulatory-evidences') regulatoryEvidenceList(@Query('requirementId')requirementId?:string){return this.s.regulatoryEvidenceList(requirementId)}
@Post('regulatory-requirements/:id/evidences') regulatoryEvidenceCreate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryEvidenceCreate(id,b)}
@Patch('regulatory-evidences/:id') regulatoryEvidenceUpdate(@Param('id')id:string,@Body()b:any){return this.s.regulatoryEvidenceUpdate(id,b)}
@Delete('regulatory-evidences/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) regulatoryEvidenceDelete(@Param('id')id:string){return this.s.regulatoryEvidenceDelete(id)}
@Post('regulatory-requirements/:id/link-risk') regulatoryLinkRisk(@Param('id')id:string,@Body()b:any){return this.s.regulatoryLinkRisk(id,b)}
@Delete('regulatory-requirement-risks/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) regulatoryUnlinkRisk(@Param('id')id:string){return this.s.regulatoryUnlinkRisk(id)}
@Post('regulatory-requirements/:id/link-document') regulatoryLinkDocument(@Param('id')id:string,@Body()b:any){return this.s.regulatoryLinkDocument(id,b)}
@Delete('regulatory-requirement-documents/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) regulatoryUnlinkDocument(@Param('id')id:string){return this.s.regulatoryUnlinkDocument(id)}
@Post('regulatory-requirements/:id/generate-nc') regulatoryGenerateNc(@Param('id')id:string,@Body()b:any){return this.s.regulatoryGenerateNc(id,b)}
@Post('regulatory-requirements/:id/generate-action') regulatoryGenerateAction(@Param('id')id:string,@Body()b:any){return this.s.regulatoryGenerateAction(id,b)}
@Get('objectifs-qhse') objectifList(@Query('famille')famille?:string,@Query('statut')statut?:string,@Query('responsableId')responsableId?:string,@Query('siteId')siteId?:string,@Query('priorite')priorite?:string,@Query('archived')archived?:string){return this.s.objectifList({famille,statut,responsableId,siteId,priorite,archived})}
@Get('objectifs-qhse/dashboard') objectifDashboard(@Query('famille')famille?:string,@Query('siteId')siteId?:string,@Query('responsableId')responsableId?:string){return this.s.objectifDashboard({famille,siteId,responsableId})}
@Get('objectifs-qhse/alertes') objectifAlertes(@Query('famille')famille?:string,@Query('siteId')siteId?:string,@Query('responsableId')responsableId?:string){return this.s.objectifAlertes({famille,siteId,responsableId})}
@Get('objectifs-qhse/library') objectifLibrary(){return this.s.objectifLibrary()}
@Get('objectifs-qhse/kpi-catalog') objectifKpiCatalog(){return this.s.objectifKpiCatalog()}
@Get('objectifs-qhse/recette') objectifRecetteList(){return this.s.objectifRecetteList()} @Patch('objectifs-qhse/recette/:id') objectifRecetteUpdate(@Param('id')id:string,@Body()b:any){return this.s.objectifRecetteUpdate(id,b)}
@Get('objectifs-qhse/:id') objectifGet(@Param('id')id:string){return this.s.objectifGet(id)}
@Get('objectifs-qhse/:id/history') objectifHistory(@Param('id')id:string){return this.s.objectifHistory(id)}
@Post('objectifs-qhse') objectifCreate(@Body()b:any){return this.s.objectifCreate(b)}
@Patch('objectifs-qhse/:id') objectifUpdate(@Param('id')id:string,@Body()b:any){return this.s.objectifUpdate(id,b)}
@Delete('objectifs-qhse/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) objectifDelete(@Param('id')id:string){return this.s.objectifDelete(id)}
@Post('objectifs-qhse/:id/restore') objectifRestore(@Param('id')id:string){return this.s.objectifRestore(id)}
@Post('objectifs-qhse/:id/duplicate') objectifDuplicate(@Param('id')id:string,@Body()b:any){return this.s.objectifDuplicate(id,b)}
@Post('objectifs-qhse/:id/kpis') objectifKpiCreate(@Param('id')id:string,@Body()b:any){return this.s.objectifKpiCreate(id,b)} @Patch('objectifs-qhse-kpis/:id') objectifKpiUpdate(@Param('id')id:string,@Body()b:any){return this.s.objectifKpiUpdate(id,b)} @Delete('objectifs-qhse-kpis/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) objectifKpiDelete(@Param('id')id:string){return this.s.objectifKpiDelete(id)}
@Post('objectifs-qhse/:id/actions') objectifActionCreate(@Param('id')id:string,@Body()b:any){return this.s.objectifActionCreate(id,b)}
@Post('objectifs-qhse/:id/actions/:actionId/link') objectifActionLink(@Param('id')id:string,@Param('actionId')actionId:string){return this.s.objectifActionLink(id,actionId)}
@Post('objectifs-qhse-actions/:actionId/unlink') objectifActionUnlink(@Param('actionId')actionId:string){return this.s.objectifActionUnlink(actionId)}
@Post('objectifs-qhse/:id/risks') objectifRiskLink(@Param('id')id:string,@Body()b:any){return this.s.objectifRiskLink(id,b)} @Delete('objectifs-qhse-risks/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) objectifRiskUnlink(@Param('id')id:string){return this.s.objectifRiskUnlink(id)}
@Get('objectifs-qhse/:id/comments') objectifCommentList(@Param('id')id:string){return this.s.objectifCommentList(id)} @Post('objectifs-qhse/:id/comments') objectifCommentCreate(@Param('id')id:string,@Body()b:any){return this.s.objectifCommentCreate(id,b)}
@Get('objectifs-qhse/:id/reviews') objectifReviewList(@Param('id')id:string){return this.s.objectifReviewList(id)} @Post('objectifs-qhse/:id/reviews') objectifReviewCreate(@Param('id')id:string,@Body()b:any){return this.s.objectifReviewCreate(id,b)}
@Get('worked-hours') workedHoursList(){return this.s.workedHoursList()} @Post('worked-hours') workedHoursCreate(@Body()b:any){return this.s.workedHoursCreate(b)} @Patch('worked-hours/:id') workedHoursUpdate(@Param('id')id:string,@Body()b:any){return this.s.workedHoursUpdate(id,b)} @Delete('worked-hours/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) workedHoursDelete(@Param('id')id:string){return this.s.workedHoursDelete(id)}
@Get('company-identity') companyIdentityGet(){return this.s.companyIdentityGet()}
@Patch('company-identity') companyIdentityUpdate(@Body()b:any){return this.s.companyIdentityUpdate(b)}
@Get('rapports/consolide') rapportConsolide(@Query('from')from?:string,@Query('to')to?:string,@Query('siteId')siteId?:string){return this.s.rapportConsolide({from,to,siteId})}
@Get('rapports') rapportList(@Query('statut')statut?:string,@Query('siteId')siteId?:string){return this.s.rapportList({statut,siteId})}
@Get('rapports/:id') rapportGet(@Param('id')id:string){return this.s.rapportGet(id)}
@Post('rapports') rapportCreate(@Body()b:any){return this.s.rapportCreate(b)}
@Patch('rapports/:id') rapportUpdate(@Param('id')id:string,@Body()b:any){return this.s.rapportUpdate(id,b)}
@Post('rapports/:id/valider') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) rapportValider(@Param('id')id:string,@Body()b:any){return this.s.rapportValider(id,b)}
@Post('rapports/:id/revision') rapportRevision(@Param('id')id:string){return this.s.rapportRevision(id)}
@Post('rapports/:id/distribuer') rapportDistribuer(@Param('id')id:string,@Body()b:any){return this.s.rapportDistribuer(id,b)}
  @Post('rapports/:id/pdf') rapportGenererPdf(@Param('id')id:string){return this.s.rapportGenererPdf(id)}
  @Post('rapports/:id/archiver-ged') rapportArchiverGed(@Param('id')id:string,@Body()b:any){return this.s.rapportArchiverGed(id,b)}
}
