import {Body,Controller,Delete,Get,Param,Patch,Post,Query} from '@nestjs/common'; import {BusinessService} from './business.service';
@Controller('business') export class BusinessController {constructor(private s:BusinessService){}
@Get('dashboard') dashboard(){return this.s.dashboard()}
@Get('quality-controls') qualityList(){return this.s.qualityList()} @Post('quality-controls') qualityCreate(@Body() b:any){return this.s.qualityCreate(b)} @Patch('quality-controls/:id') qualityUpdate(@Param('id')id:string,@Body()b:any){return this.s.qualityUpdate(id,b)} @Delete('quality-controls/:id') qualityDelete(@Param('id')id:string){return this.s.qualityDelete(id)}
@Get('non-conformities') ncList(@Query('status')status?:string){return this.s.ncList(status)} @Post('non-conformities') ncCreate(@Body()b:any){return this.s.ncCreate(b)} @Patch('non-conformities/:id') ncUpdate(@Param('id')id:string,@Body()b:any){return this.s.ncUpdate(id,b)} @Delete('non-conformities/:id') ncDelete(@Param('id')id:string){return this.s.ncDelete(id)}
@Get('actions') actionList(@Query('status')status?:string){return this.s.actionList(status)} @Post('actions') actionCreate(@Body()b:any){return this.s.actionCreate(b)} @Patch('actions/:id') actionUpdate(@Param('id')id:string,@Body()b:any){return this.s.actionUpdate(id,b)} @Delete('actions/:id') actionDelete(@Param('id')id:string){return this.s.actionDelete(id)}
@Get('risks') riskList(){return this.s.riskList()} @Post('risks') riskCreate(@Body()b:any){return this.s.riskCreate(b)} @Patch('risks/:id') riskUpdate(@Param('id')id:string,@Body()b:any){return this.s.riskUpdate(id,b)} @Delete('risks/:id') riskDelete(@Param('id')id:string){return this.s.riskDelete(id)}
@Get('haccp') haccpList(){return this.s.haccpList()} @Post('haccp') haccpCreate(@Body()b:any){return this.s.haccpCreate(b)} @Patch('haccp/:id') haccpUpdate(@Param('id')id:string,@Body()b:any){return this.s.haccpUpdate(id,b)}
@Get('audits') auditList(){return this.s.auditList()} @Post('audits') auditCreate(@Body()b:any){return this.s.auditCreate(b)} @Patch('audits/:id') auditUpdate(@Param('id')id:string,@Body()b:any){return this.s.auditUpdate(id,b)}
@Get('environment') envList(){return this.s.envList()} @Post('environment') envCreate(@Body()b:any){return this.s.envCreate(b)} @Patch('environment/:id') envUpdate(@Param('id')id:string,@Body()b:any){return this.s.envUpdate(id,b)} @Delete('environment/:id') envDelete(@Param('id')id:string){return this.s.envDelete(id)}
@Get('trainings') trainingList(){return this.s.trainingList()} @Post('trainings') trainingCreate(@Body()b:any){return this.s.trainingCreate(b)} @Patch('trainings/:id') trainingUpdate(@Param('id')id:string,@Body()b:any){return this.s.trainingUpdate(id,b)}
@Get('equipment') equipmentList(){return this.s.equipmentList()} @Post('equipment') equipmentCreate(@Body()b:any){return this.s.equipmentCreate(b)} @Patch('equipment/:id') equipmentUpdate(@Param('id')id:string,@Body()b:any){return this.s.equipmentUpdate(id,b)}
@Get('safety-events') events(){return this.s.events()} @Post('safety-events') eventCreate(@Body()b:any){return this.s.eventCreate(b)} @Patch('safety-events/:id') eventUpdate(@Param('id')id:string,@Body()b:any){return this.s.eventUpdate(id,b)} @Delete('safety-events/:id') eventDelete(@Param('id')id:string){return this.s.eventDelete(id)}
@Get('processus') processusList(){return this.s.processusList()} @Post('processus') processusCreate(@Body()b:any){return this.s.processusCreate(b)} @Patch('processus/:id') processusUpdate(@Param('id')id:string,@Body()b:any){return this.s.processusUpdate(id,b)} @Delete('processus/:id') processusDelete(@Param('id')id:string){return this.s.processusDelete(id)}
@Get('indicateurs-qualite') indicateurList(){return this.s.indicateurList()} @Post('indicateurs-qualite') indicateurCreate(@Body()b:any){return this.s.indicateurCreate(b)} @Patch('indicateurs-qualite/:id') indicateurUpdate(@Param('id')id:string,@Body()b:any){return this.s.indicateurUpdate(id,b)} @Delete('indicateurs-qualite/:id') indicateurDelete(@Param('id')id:string){return this.s.indicateurDelete(id)}
@Get('reclamations') reclamationList(){return this.s.reclamationList()} @Post('reclamations') reclamationCreate(@Body()b:any){return this.s.reclamationCreate(b)} @Patch('reclamations/:id') reclamationUpdate(@Param('id')id:string,@Body()b:any){return this.s.reclamationUpdate(id,b)} @Delete('reclamations/:id') reclamationDelete(@Param('id')id:string){return this.s.reclamationDelete(id)}
@Get('fournisseurs') fournisseurList(){return this.s.fournisseurList()} @Post('fournisseurs') fournisseurCreate(@Body()b:any){return this.s.fournisseurCreate(b)} @Patch('fournisseurs/:id') fournisseurUpdate(@Param('id')id:string,@Body()b:any){return this.s.fournisseurUpdate(id,b)} @Delete('fournisseurs/:id') fournisseurDelete(@Param('id')id:string){return this.s.fournisseurDelete(id)}
@Get('visites-medicales') visiteMedicaleList(){return this.s.visiteMedicaleList()} @Post('visites-medicales') visiteMedicaleCreate(@Body()b:any){return this.s.visiteMedicaleCreate(b)} @Patch('visites-medicales/:id') visiteMedicaleUpdate(@Param('id')id:string,@Body()b:any){return this.s.visiteMedicaleUpdate(id,b)} @Delete('visites-medicales/:id') visiteMedicaleDelete(@Param('id')id:string){return this.s.visiteMedicaleDelete(id)}
@Get('veille-reglementaire') veilleList(){return this.s.veilleList()} @Post('veille-reglementaire') veilleCreate(@Body()b:any){return this.s.veilleCreate(b)} @Patch('veille-reglementaire/:id') veilleUpdate(@Param('id')id:string,@Body()b:any){return this.s.veilleUpdate(id,b)} @Delete('veille-reglementaire/:id') veilleDelete(@Param('id')id:string){return this.s.veilleDelete(id)}
@Get('objectifs-qhse') objectifList(){return this.s.objectifList()} @Post('objectifs-qhse') objectifCreate(@Body()b:any){return this.s.objectifCreate(b)} @Patch('objectifs-qhse/:id') objectifUpdate(@Param('id')id:string,@Body()b:any){return this.s.objectifUpdate(id,b)} @Delete('objectifs-qhse/:id') objectifDelete(@Param('id')id:string){return this.s.objectifDelete(id)} }
