import { Roles } from '../common/roles.decorator';
import { RoleName } from '@prisma/client';
import {Body,Controller,Delete,Get,Param,Patch,Post,Query} from '@nestjs/common'; import {EpiService} from './epi.service';
import { CreateEmployeeDto,UpdateEmployeeDto,CreateEpiDto,UpdateEpiDto,CreateEpiMovementDto,CreateEpiCategoryDto,UpdateEpiCategoryDto,CreateEpcCategoryDto,UpdateEpcCategoryDto,CreateEpcDto,UpdateEpcDto,CreateEpiInspectionDto,CreateEpcInspectionDto,CreateJobRiskProtectionDto,UpdateJobRiskProtectionDto,CreateEpiAssignmentDto,UpdateEpiAssignmentDto,CreateEpcMaintenanceDto,UpdateEpcMaintenanceDto } from './epi.dto';
@Controller('epi') export class EpiController{constructor(private s:EpiService){} @Get('dashboard') dashboard(){return this.s.dashboard()} @Get('renewals') renewals(@Query('days') days?:string){return this.s.annualRenewals(days?Number(days):30)}
@Get('employees') employeeList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.employeeList(take?Number(take):undefined,skip?Number(skip):undefined)} @Get('employees/:id/dossier') employeeDossier(@Param('id')id:string){return this.s.employeeDossier(id)} @Post('employees') employeeCreate(@Body()b:CreateEmployeeDto){return this.s.employeeCreate(b)} @Patch('employees/:id') employeeUpdate(@Param('id')id:string,@Body()b:UpdateEmployeeDto){return this.s.employeeUpdate(id,b)} @Delete('employees/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) employeeDelete(@Param('id')id:string){return this.s.employeeDelete(id)}
@Get('catalog') catalogList(){return this.s.catalogList()} @Post('catalog') catalogCreate(@Body()b:CreateEpiDto){return this.s.catalogCreate(b)} @Patch('catalog/:id') catalogUpdate(@Param('id')id:string,@Body()b:UpdateEpiDto){return this.s.catalogUpdate(id,b)} @Delete('catalog/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) catalogDelete(@Param('id')id:string){return this.s.catalogDelete(id)}
@Post('movements') movementCreate(@Body()b:CreateEpiMovementDto){return this.s.movementCreate(b)}
@Get('epi-categories') epiCategoryList(){return this.s.epiCategoryList()} @Post('epi-categories') epiCategoryCreate(@Body()b:CreateEpiCategoryDto){return this.s.epiCategoryCreate(b)} @Patch('epi-categories/:id') epiCategoryUpdate(@Param('id')id:string,@Body()b:UpdateEpiCategoryDto){return this.s.epiCategoryUpdate(id,b)} @Delete('epi-categories/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) epiCategoryDelete(@Param('id')id:string){return this.s.epiCategoryDelete(id)}
@Get('epc-categories') epcCategoryList(){return this.s.epcCategoryList()} @Post('epc-categories') epcCategoryCreate(@Body()b:CreateEpcCategoryDto){return this.s.epcCategoryCreate(b)} @Patch('epc-categories/:id') epcCategoryUpdate(@Param('id')id:string,@Body()b:UpdateEpcCategoryDto){return this.s.epcCategoryUpdate(id,b)} @Delete('epc-categories/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) epcCategoryDelete(@Param('id')id:string){return this.s.epcCategoryDelete(id)}
@Get('epc') epcList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.epcList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('epc') epcCreate(@Body()b:CreateEpcDto){return this.s.epcCreate(b)} @Patch('epc/:id') epcUpdate(@Param('id')id:string,@Body()b:UpdateEpcDto){return this.s.epcUpdate(id,b)} @Delete('epc/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) epcDelete(@Param('id')id:string){return this.s.epcDelete(id)}
@Get('epi-inspections') epiInspectionList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.epiInspectionList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('epi-inspections') epiInspectionCreate(@Body()b:CreateEpiInspectionDto){return this.s.epiInspectionCreate(b)}
@Get('epc-inspections') epcInspectionList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.epcInspectionList(take?Number(take):undefined,skip?Number(skip):undefined)} @Post('epc-inspections') epcInspectionCreate(@Body()b:CreateEpcInspectionDto){return this.s.epcInspectionCreate(b)}
@Get('job-risk-protection') jobRiskProtectionList(){return this.s.jobRiskProtectionList()} @Post('job-risk-protection') jobRiskProtectionCreate(@Body()b:CreateJobRiskProtectionDto){return this.s.jobRiskProtectionCreate(b)} @Patch('job-risk-protection/:id') jobRiskProtectionUpdate(@Param('id')id:string,@Body()b:UpdateJobRiskProtectionDto){return this.s.jobRiskProtectionUpdate(id,b)} @Delete('job-risk-protection/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) jobRiskProtectionDelete(@Param('id')id:string){return this.s.jobRiskProtectionDelete(id)}
@Get('assignments') assignmentList(@Query('take')take?:string,@Query('skip')skip?:string){return this.s.assignmentList(take?Number(take):undefined,skip?Number(skip):undefined)} @Get('assignments/:id') assignmentGet(@Param('id')id:string){return this.s.assignmentGet(id)} @Post('assignments') assignmentCreate(@Body()b:CreateEpiAssignmentDto){return this.s.assignmentCreate(b)} @Patch('assignments/:id') assignmentUpdate(@Param('id')id:string,@Body()b:UpdateEpiAssignmentDto){return this.s.assignmentUpdate(id,b)}
@Get('renewal-buckets') renewalBuckets(){return this.s.renewalBuckets()}
@Get('maintenance') maintenanceList(@Query('epcId')epcId?:string){return this.s.maintenanceList(epcId)} @Post('maintenance') maintenanceCreate(@Body()b:CreateEpcMaintenanceDto){return this.s.maintenanceCreate(b)} @Patch('maintenance/:id') maintenanceUpdate(@Param('id')id:string,@Body()b:UpdateEpcMaintenanceDto){return this.s.maintenanceUpdate(id,b)} @Delete('maintenance/:id') @Roles(RoleName.ADMINISTRATEUR,RoleName.RESPONSABLE_QHSE) maintenanceDelete(@Param('id')id:string){return this.s.maintenanceDelete(id)}
}
