import {Body,Controller,Delete,Get,Param,Patch,Post,Query} from '@nestjs/common'; import {EpiService} from './epi.service'; @Controller('epi') export class EpiController{constructor(private s:EpiService){} @Get('dashboard') dashboard(){return this.s.dashboard()} @Get('renewals') renewals(@Query('days') days?:string){return this.s.annualRenewals(days?Number(days):30)}
@Get('employees') employeeList(){return this.s.employeeList()} @Post('employees') employeeCreate(@Body()b:any){return this.s.employeeCreate(b)} @Patch('employees/:id') employeeUpdate(@Param('id')id:string,@Body()b:any){return this.s.employeeUpdate(id,b)} @Delete('employees/:id') employeeDelete(@Param('id')id:string){return this.s.employeeDelete(id)}
@Get('catalog') catalogList(){return this.s.catalogList()} @Post('catalog') catalogCreate(@Body()b:any){return this.s.catalogCreate(b)} @Patch('catalog/:id') catalogUpdate(@Param('id')id:string,@Body()b:any){return this.s.catalogUpdate(id,b)} @Delete('catalog/:id') catalogDelete(@Param('id')id:string){return this.s.catalogDelete(id)}
@Post('movements') movementCreate(@Body()b:any){return this.s.movementCreate(b)}
@Get('epi-categories') epiCategoryList(){return this.s.epiCategoryList()} @Post('epi-categories') epiCategoryCreate(@Body()b:any){return this.s.epiCategoryCreate(b)} @Patch('epi-categories/:id') epiCategoryUpdate(@Param('id')id:string,@Body()b:any){return this.s.epiCategoryUpdate(id,b)} @Delete('epi-categories/:id') epiCategoryDelete(@Param('id')id:string){return this.s.epiCategoryDelete(id)}
@Get('epc-categories') epcCategoryList(){return this.s.epcCategoryList()} @Post('epc-categories') epcCategoryCreate(@Body()b:any){return this.s.epcCategoryCreate(b)} @Patch('epc-categories/:id') epcCategoryUpdate(@Param('id')id:string,@Body()b:any){return this.s.epcCategoryUpdate(id,b)} @Delete('epc-categories/:id') epcCategoryDelete(@Param('id')id:string){return this.s.epcCategoryDelete(id)}
@Get('epc') epcList(){return this.s.epcList()} @Post('epc') epcCreate(@Body()b:any){return this.s.epcCreate(b)} @Patch('epc/:id') epcUpdate(@Param('id')id:string,@Body()b:any){return this.s.epcUpdate(id,b)} @Delete('epc/:id') epcDelete(@Param('id')id:string){return this.s.epcDelete(id)}
@Get('epi-inspections') epiInspectionList(){return this.s.epiInspectionList()} @Post('epi-inspections') epiInspectionCreate(@Body()b:any){return this.s.epiInspectionCreate(b)}
@Get('epc-inspections') epcInspectionList(){return this.s.epcInspectionList()} @Post('epc-inspections') epcInspectionCreate(@Body()b:any){return this.s.epcInspectionCreate(b)}
@Get('job-risk-protection') jobRiskProtectionList(){return this.s.jobRiskProtectionList()} @Post('job-risk-protection') jobRiskProtectionCreate(@Body()b:any){return this.s.jobRiskProtectionCreate(b)} @Patch('job-risk-protection/:id') jobRiskProtectionUpdate(@Param('id')id:string,@Body()b:any){return this.s.jobRiskProtectionUpdate(id,b)} @Delete('job-risk-protection/:id') jobRiskProtectionDelete(@Param('id')id:string){return this.s.jobRiskProtectionDelete(id)}
@Get('assignments') assignmentList(){return this.s.assignmentList()} @Get('assignments/:id') assignmentGet(@Param('id')id:string){return this.s.assignmentGet(id)} @Post('assignments') assignmentCreate(@Body()b:any){return this.s.assignmentCreate(b)} @Patch('assignments/:id') assignmentUpdate(@Param('id')id:string,@Body()b:any){return this.s.assignmentUpdate(id,b)}
@Get('renewal-buckets') renewalBuckets(){return this.s.renewalBuckets()}
@Get('maintenance') maintenanceList(@Query('epcId')epcId?:string){return this.s.maintenanceList(epcId)} @Post('maintenance') maintenanceCreate(@Body()b:any){return this.s.maintenanceCreate(b)} @Patch('maintenance/:id') maintenanceUpdate(@Param('id')id:string,@Body()b:any){return this.s.maintenanceUpdate(id,b)} @Delete('maintenance/:id') maintenanceDelete(@Param('id')id:string){return this.s.maintenanceDelete(id)}
}
